apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
  name: cloudbuild-gchat
  namespace: "330311169810"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 80
      containers:
        - env:
            - name: LOG_VERBOSITY
              value: "1"
            - name: LOG_FORMAT
              value: json+gcp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: lucid.liao.dev:4317
            - name: OTLP_AUDIENCE
              value: https://lucid.liao.dev
            - name: GCHAT_WEBHOOK
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: cloudbuild-gchat-webhook
          image: us-central1-docker.pkg.dev/com-seankhliao/run/cloudbuild-gchat
          ports:
            - containerPort: 8080
              name: h2c
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
      serviceAccountName: cloudbuild-gchat@com-seankhliao.iam.gserviceaccount.com
      timeoutSeconds: 5
  traffic:
    - latestRevision: true
      percent: 100
